---
- name: Apt update
  apt:
    update_cache: yes

- name: Restart Jenkins
  systemd:
    name: jenkins
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true