---
- import_tasks: install.yml
- import_tasks: ingress_tls.yml
  when: microk8s_ingress_enable | bool

- import_tasks: metallb.yml
  when: microk8s_enable_metallb | default(false) | bool

- import_tasks: healthcheck.yml